from PyQt5 import QtCore, QtGui, QtWidgets
from quirks.mainApp import _register
import homePage,noDetailsError

class Ui_registerPage(object):

    def clickedRegister(self, registerPage, welcomePage):
        email = self.lineEdit.text()
        password = self.lineEdit_2.text()
        phNum = self.lineEdit_3.text()
        if email !='' and password != '' and phNum != '':
            self.userid = _register.registration(email,password,phNum)
            if self.userid:
                self.homePage = QtWidgets.QMainWindow()
                self.homeui = homePage.Ui_homePage()
                self.homeui.setupUi(self.homePage)
                self.homePage.show()
                registerPage.close()
                welcomePage.close()
                self.homeui.userID = self.userid
                self.homeui.getEmail(self.userid)
        else:
            self.detailsError = QtWidgets.QMainWindow()
            self.detailsErrorui = noDetailsError.Ui_loginFail()
            self.detailsErrorui.setupUi(self.detailsError)
            self.detailsError.show()

    def setupUi(self, registerPage, welcomePage):
        registerPage.setObjectName("registerPage")
        registerPage.resize(503, 373)
        registerPage.setMinimumSize(QtCore.QSize(503, 373))
        registerPage.setMaximumSize(QtCore.QSize(503, 373))
        self.centralwidget = QtWidgets.QWidget(registerPage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 40, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 200, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 75, 390, 20))
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 155, 390, 20))
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setMaxLength(10)
        self.lineEdit_3.setValidator(QtGui.QIntValidator())
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 235, 390, 20))
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.cancleButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: registerPage.close())
        self.cancleButton.setGeometry(QtCore.QRect(370, 280, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancleButton.setFont(font)
        self.cancleButton.setObjectName("cancleButton")
        self.loginButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.clickedRegister(registerPage,welcomePage))
        self.loginButton.setGeometry(QtCore.QRect(260, 280, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("loginButton")
        registerPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(registerPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 503, 21))
        self.menubar.setObjectName("menubar")
        registerPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(registerPage)
        self.statusbar.setObjectName("statusbar")
        registerPage.setStatusBar(self.statusbar)

        self.retranslateUi(registerPage)
        QtCore.QMetaObject.connectSlotsByName(registerPage)

    def retranslateUi(self, registerPage):
        _translate = QtCore.QCoreApplication.translate
        registerPage.setWindowTitle(_translate("registerPage", "Register"))
        registerPage.setWindowIcon(QtGui.QIcon("icon.png"))
        self.label.setText(_translate("registerPage", "EMAIL"))
        self.label_2.setText(_translate("registerPage", "PASSSWORD"))
        self.label_3.setText(_translate("registerPage", "PHONE NUMBER"))
        self.cancleButton.setText(_translate("registerPage", "CANCEL"))
        self.loginButton.setText(_translate("registerPage", "REGISTER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    registerPage = QtWidgets.QMainWindow()
    ui = Ui_registerPage()
    ui.setupUi(registerPage)
    registerPage.show()
    sys.exit(app.exec_())
